#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CdSite
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CdSite")]
	public partial class veriDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdt_film(dt_film instance);
    partial void Updatedt_film(dt_film instance);
    partial void Deletedt_film(dt_film instance);
    partial void Insertdt_kullanici(dt_kullanici instance);
    partial void Updatedt_kullanici(dt_kullanici instance);
    partial void Deletedt_kullanici(dt_kullanici instance);
    partial void Insertdt_muzik(dt_muzik instance);
    partial void Updatedt_muzik(dt_muzik instance);
    partial void Deletedt_muzik(dt_muzik instance);
    partial void Insertdt_oyun(dt_oyun instance);
    partial void Updatedt_oyun(dt_oyun instance);
    partial void Deletedt_oyun(dt_oyun instance);
    partial void Insertlu_filmTur(lu_filmTur instance);
    partial void Updatelu_filmTur(lu_filmTur instance);
    partial void Deletelu_filmTur(lu_filmTur instance);
    partial void Insertlu_oyunTur(lu_oyunTur instance);
    partial void Updatelu_oyunTur(lu_oyunTur instance);
    partial void Deletelu_oyunTur(lu_oyunTur instance);
    partial void Inserttx_filmKira(tx_filmKira instance);
    partial void Updatetx_filmKira(tx_filmKira instance);
    partial void Deletetx_filmKira(tx_filmKira instance);
    partial void Inserttx_sati(tx_sati instance);
    partial void Updatetx_sati(tx_sati instance);
    partial void Deletetx_sati(tx_sati instance);
    partial void Insertlu_muzikTur(lu_muzikTur instance);
    partial void Updatelu_muzikTur(lu_muzikTur instance);
    partial void Deletelu_muzikTur(lu_muzikTur instance);
    #endregion
		
		public veriDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CdSiteConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public veriDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public veriDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public veriDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public veriDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dt_film> dt_films
		{
			get
			{
				return this.GetTable<dt_film>();
			}
		}
		
		public System.Data.Linq.Table<dt_kullanici> dt_kullanicis
		{
			get
			{
				return this.GetTable<dt_kullanici>();
			}
		}
		
		public System.Data.Linq.Table<dt_muzik> dt_muziks
		{
			get
			{
				return this.GetTable<dt_muzik>();
			}
		}
		
		public System.Data.Linq.Table<dt_oyun> dt_oyuns
		{
			get
			{
				return this.GetTable<dt_oyun>();
			}
		}
		
		public System.Data.Linq.Table<lu_filmTur> lu_filmTurs
		{
			get
			{
				return this.GetTable<lu_filmTur>();
			}
		}
		
		public System.Data.Linq.Table<lu_oyunTur> lu_oyunTurs
		{
			get
			{
				return this.GetTable<lu_oyunTur>();
			}
		}
		
		public System.Data.Linq.Table<tx_filmKira> tx_filmKiras
		{
			get
			{
				return this.GetTable<tx_filmKira>();
			}
		}
		
		public System.Data.Linq.Table<tx_sati> tx_satis
		{
			get
			{
				return this.GetTable<tx_sati>();
			}
		}
		
		public System.Data.Linq.Table<lu_muzikTur> lu_muzikTurs
		{
			get
			{
				return this.GetTable<lu_muzikTur>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_film")]
	public partial class dt_film : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ad;
		
		private short _yapimYil;
		
		private string _yapimci;
		
		private System.TimeSpan _sure;
		
		private string _barkod;
		
		private short _adet;
		
		private double _fiyat;
		
		private short _filmTur_id;
		
		private EntitySet<tx_sati> _tx_satis;
		
		private EntityRef<lu_filmTur> _lu_filmTur;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnyapimYilChanging(short value);
    partial void OnyapimYilChanged();
    partial void OnyapimciChanging(string value);
    partial void OnyapimciChanged();
    partial void OnsureChanging(System.TimeSpan value);
    partial void OnsureChanged();
    partial void OnbarkodChanging(string value);
    partial void OnbarkodChanged();
    partial void OnadetChanging(short value);
    partial void OnadetChanged();
    partial void OnfiyatChanging(double value);
    partial void OnfiyatChanged();
    partial void OnfilmTur_idChanging(short value);
    partial void OnfilmTur_idChanged();
    #endregion
		
		public dt_film()
		{
			this._tx_satis = new EntitySet<tx_sati>(new Action<tx_sati>(this.attach_tx_satis), new Action<tx_sati>(this.detach_tx_satis));
			this._lu_filmTur = default(EntityRef<lu_filmTur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yapimYil", DbType="SmallInt NOT NULL")]
		public short yapimYil
		{
			get
			{
				return this._yapimYil;
			}
			set
			{
				if ((this._yapimYil != value))
				{
					this.OnyapimYilChanging(value);
					this.SendPropertyChanging();
					this._yapimYil = value;
					this.SendPropertyChanged("yapimYil");
					this.OnyapimYilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yapimci", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string yapimci
		{
			get
			{
				return this._yapimci;
			}
			set
			{
				if ((this._yapimci != value))
				{
					this.OnyapimciChanging(value);
					this.SendPropertyChanging();
					this._yapimci = value;
					this.SendPropertyChanged("yapimci");
					this.OnyapimciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sure", DbType="Time NOT NULL")]
		public System.TimeSpan sure
		{
			get
			{
				return this._sure;
			}
			set
			{
				if ((this._sure != value))
				{
					this.OnsureChanging(value);
					this.SendPropertyChanging();
					this._sure = value;
					this.SendPropertyChanged("sure");
					this.OnsureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barkod", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string barkod
		{
			get
			{
				return this._barkod;
			}
			set
			{
				if ((this._barkod != value))
				{
					this.OnbarkodChanging(value);
					this.SendPropertyChanging();
					this._barkod = value;
					this.SendPropertyChanged("barkod");
					this.OnbarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="SmallInt NOT NULL")]
		public short adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this.OnadetChanging(value);
					this.SendPropertyChanging();
					this._adet = value;
					this.SendPropertyChanged("adet");
					this.OnadetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="Float NOT NULL")]
		public double fiyat
		{
			get
			{
				return this._fiyat;
			}
			set
			{
				if ((this._fiyat != value))
				{
					this.OnfiyatChanging(value);
					this.SendPropertyChanging();
					this._fiyat = value;
					this.SendPropertyChanged("fiyat");
					this.OnfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filmTur_id", DbType="SmallInt NOT NULL")]
		public short filmTur_id
		{
			get
			{
				return this._filmTur_id;
			}
			set
			{
				if ((this._filmTur_id != value))
				{
					if (this._lu_filmTur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfilmTur_idChanging(value);
					this.SendPropertyChanging();
					this._filmTur_id = value;
					this.SendPropertyChanged("filmTur_id");
					this.OnfilmTur_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_film_tx_sati", Storage="_tx_satis", ThisKey="id", OtherKey="film_id")]
		public EntitySet<tx_sati> tx_satis
		{
			get
			{
				return this._tx_satis;
			}
			set
			{
				this._tx_satis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lu_filmTur_dt_film", Storage="_lu_filmTur", ThisKey="filmTur_id", OtherKey="id", IsForeignKey=true)]
		public lu_filmTur lu_filmTur
		{
			get
			{
				return this._lu_filmTur.Entity;
			}
			set
			{
				lu_filmTur previousValue = this._lu_filmTur.Entity;
				if (((previousValue != value) 
							|| (this._lu_filmTur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lu_filmTur.Entity = null;
						previousValue.dt_films.Remove(this);
					}
					this._lu_filmTur.Entity = value;
					if ((value != null))
					{
						value.dt_films.Add(this);
						this._filmTur_id = value.id;
					}
					else
					{
						this._filmTur_id = default(short);
					}
					this.SendPropertyChanged("lu_filmTur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tx_satis(tx_sati entity)
		{
			this.SendPropertyChanging();
			entity.dt_film = this;
		}
		
		private void detach_tx_satis(tx_sati entity)
		{
			this.SendPropertyChanging();
			entity.dt_film = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_kullanici")]
	public partial class dt_kullanici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ad;
		
		private string _soyad;
		
		private decimal _tcNo;
		
		private System.DateTime _dogumTarih;
		
		private string _eposta;
		
		private string _sifre;
		
		private bool _yetki;
		
		private EntitySet<tx_filmKira> _tx_filmKiras;
		
		private EntitySet<tx_sati> _tx_satis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsoyadChanging(string value);
    partial void OnsoyadChanged();
    partial void OntcNoChanging(decimal value);
    partial void OntcNoChanged();
    partial void OndogumTarihChanging(System.DateTime value);
    partial void OndogumTarihChanged();
    partial void OnepostaChanging(string value);
    partial void OnepostaChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OnyetkiChanging(bool value);
    partial void OnyetkiChanged();
    #endregion
		
		public dt_kullanici()
		{
			this._tx_filmKiras = new EntitySet<tx_filmKira>(new Action<tx_filmKira>(this.attach_tx_filmKiras), new Action<tx_filmKira>(this.detach_tx_filmKiras));
			this._tx_satis = new EntitySet<tx_sati>(new Action<tx_sati>(this.attach_tx_satis), new Action<tx_sati>(this.detach_tx_satis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string soyad
		{
			get
			{
				return this._soyad;
			}
			set
			{
				if ((this._soyad != value))
				{
					this.OnsoyadChanging(value);
					this.SendPropertyChanging();
					this._soyad = value;
					this.SendPropertyChanged("soyad");
					this.OnsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tcNo", DbType="Decimal(11,0) NOT NULL")]
		public decimal tcNo
		{
			get
			{
				return this._tcNo;
			}
			set
			{
				if ((this._tcNo != value))
				{
					this.OntcNoChanging(value);
					this.SendPropertyChanging();
					this._tcNo = value;
					this.SendPropertyChanged("tcNo");
					this.OntcNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dogumTarih", DbType="Date NOT NULL")]
		public System.DateTime dogumTarih
		{
			get
			{
				return this._dogumTarih;
			}
			set
			{
				if ((this._dogumTarih != value))
				{
					this.OndogumTarihChanging(value);
					this.SendPropertyChanging();
					this._dogumTarih = value;
					this.SendPropertyChanged("dogumTarih");
					this.OndogumTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eposta", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string eposta
		{
			get
			{
				return this._eposta;
			}
			set
			{
				if ((this._eposta != value))
				{
					this.OnepostaChanging(value);
					this.SendPropertyChanging();
					this._eposta = value;
					this.SendPropertyChanged("eposta");
					this.OnepostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yetki", DbType="Bit NOT NULL")]
		public bool yetki
		{
			get
			{
				return this._yetki;
			}
			set
			{
				if ((this._yetki != value))
				{
					this.OnyetkiChanging(value);
					this.SendPropertyChanging();
					this._yetki = value;
					this.SendPropertyChanged("yetki");
					this.OnyetkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_kullanici_tx_filmKira", Storage="_tx_filmKiras", ThisKey="id", OtherKey="kullanici_id")]
		public EntitySet<tx_filmKira> tx_filmKiras
		{
			get
			{
				return this._tx_filmKiras;
			}
			set
			{
				this._tx_filmKiras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_kullanici_tx_sati", Storage="_tx_satis", ThisKey="id", OtherKey="kullanici_id")]
		public EntitySet<tx_sati> tx_satis
		{
			get
			{
				return this._tx_satis;
			}
			set
			{
				this._tx_satis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tx_filmKiras(tx_filmKira entity)
		{
			this.SendPropertyChanging();
			entity.dt_kullanici = this;
		}
		
		private void detach_tx_filmKiras(tx_filmKira entity)
		{
			this.SendPropertyChanging();
			entity.dt_kullanici = null;
		}
		
		private void attach_tx_satis(tx_sati entity)
		{
			this.SendPropertyChanging();
			entity.dt_kullanici = this;
		}
		
		private void detach_tx_satis(tx_sati entity)
		{
			this.SendPropertyChanging();
			entity.dt_kullanici = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_muzik")]
	public partial class dt_muzik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ad;
		
		private string _sanatci;
		
		private string _album;
		
		private System.TimeSpan _sure;
		
		private short _yapimYil;
		
		private short _adet;
		
		private double _fiyat;
		
		private string _barkod;
		
		private short _muzikTur_id;
		
		private EntitySet<tx_sati> _tx_satis;
		
		private EntityRef<lu_muzikTur> _lu_muzikTur;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsanatciChanging(string value);
    partial void OnsanatciChanged();
    partial void OnalbumChanging(string value);
    partial void OnalbumChanged();
    partial void OnsureChanging(System.TimeSpan value);
    partial void OnsureChanged();
    partial void OnyapimYilChanging(short value);
    partial void OnyapimYilChanged();
    partial void OnadetChanging(short value);
    partial void OnadetChanged();
    partial void OnfiyatChanging(double value);
    partial void OnfiyatChanged();
    partial void OnbarkodChanging(string value);
    partial void OnbarkodChanged();
    partial void OnmuzikTur_idChanging(short value);
    partial void OnmuzikTur_idChanged();
    #endregion
		
		public dt_muzik()
		{
			this._tx_satis = new EntitySet<tx_sati>(new Action<tx_sati>(this.attach_tx_satis), new Action<tx_sati>(this.detach_tx_satis));
			this._lu_muzikTur = default(EntityRef<lu_muzikTur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanatci", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sanatci
		{
			get
			{
				return this._sanatci;
			}
			set
			{
				if ((this._sanatci != value))
				{
					this.OnsanatciChanging(value);
					this.SendPropertyChanging();
					this._sanatci = value;
					this.SendPropertyChanged("sanatci");
					this.OnsanatciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_album", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string album
		{
			get
			{
				return this._album;
			}
			set
			{
				if ((this._album != value))
				{
					this.OnalbumChanging(value);
					this.SendPropertyChanging();
					this._album = value;
					this.SendPropertyChanged("album");
					this.OnalbumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sure", DbType="Time NOT NULL")]
		public System.TimeSpan sure
		{
			get
			{
				return this._sure;
			}
			set
			{
				if ((this._sure != value))
				{
					this.OnsureChanging(value);
					this.SendPropertyChanging();
					this._sure = value;
					this.SendPropertyChanged("sure");
					this.OnsureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yapimYil", DbType="SmallInt NOT NULL")]
		public short yapimYil
		{
			get
			{
				return this._yapimYil;
			}
			set
			{
				if ((this._yapimYil != value))
				{
					this.OnyapimYilChanging(value);
					this.SendPropertyChanging();
					this._yapimYil = value;
					this.SendPropertyChanged("yapimYil");
					this.OnyapimYilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="SmallInt NOT NULL")]
		public short adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this.OnadetChanging(value);
					this.SendPropertyChanging();
					this._adet = value;
					this.SendPropertyChanged("adet");
					this.OnadetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="Float NOT NULL")]
		public double fiyat
		{
			get
			{
				return this._fiyat;
			}
			set
			{
				if ((this._fiyat != value))
				{
					this.OnfiyatChanging(value);
					this.SendPropertyChanging();
					this._fiyat = value;
					this.SendPropertyChanged("fiyat");
					this.OnfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barkod", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string barkod
		{
			get
			{
				return this._barkod;
			}
			set
			{
				if ((this._barkod != value))
				{
					this.OnbarkodChanging(value);
					this.SendPropertyChanging();
					this._barkod = value;
					this.SendPropertyChanged("barkod");
					this.OnbarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_muzikTur_id", DbType="SmallInt NOT NULL")]
		public short muzikTur_id
		{
			get
			{
				return this._muzikTur_id;
			}
			set
			{
				if ((this._muzikTur_id != value))
				{
					if (this._lu_muzikTur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmuzikTur_idChanging(value);
					this.SendPropertyChanging();
					this._muzikTur_id = value;
					this.SendPropertyChanged("muzikTur_id");
					this.OnmuzikTur_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_muzik_tx_sati", Storage="_tx_satis", ThisKey="id", OtherKey="muzik_id")]
		public EntitySet<tx_sati> tx_satis
		{
			get
			{
				return this._tx_satis;
			}
			set
			{
				this._tx_satis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lu_muzikTur_dt_muzik", Storage="_lu_muzikTur", ThisKey="muzikTur_id", OtherKey="id", IsForeignKey=true)]
		public lu_muzikTur lu_muzikTur
		{
			get
			{
				return this._lu_muzikTur.Entity;
			}
			set
			{
				lu_muzikTur previousValue = this._lu_muzikTur.Entity;
				if (((previousValue != value) 
							|| (this._lu_muzikTur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lu_muzikTur.Entity = null;
						previousValue.dt_muziks.Remove(this);
					}
					this._lu_muzikTur.Entity = value;
					if ((value != null))
					{
						value.dt_muziks.Add(this);
						this._muzikTur_id = value.id;
					}
					else
					{
						this._muzikTur_id = default(short);
					}
					this.SendPropertyChanged("lu_muzikTur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tx_satis(tx_sati entity)
		{
			this.SendPropertyChanging();
			entity.dt_muzik = this;
		}
		
		private void detach_tx_satis(tx_sati entity)
		{
			this.SendPropertyChanging();
			entity.dt_muzik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_oyun")]
	public partial class dt_oyun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ad;
		
		private short _yapimYil;
		
		private string _yapimci;
		
		private string _platform;
		
		private string _barkod;
		
		private short _adet;
		
		private double _fiyat;
		
		private short _oyunTur_id;
		
		private EntitySet<tx_sati> _tx_satis;
		
		private EntityRef<lu_oyunTur> _lu_oyunTur;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnyapimYilChanging(short value);
    partial void OnyapimYilChanged();
    partial void OnyapimciChanging(string value);
    partial void OnyapimciChanged();
    partial void OnplatformChanging(string value);
    partial void OnplatformChanged();
    partial void OnbarkodChanging(string value);
    partial void OnbarkodChanged();
    partial void OnadetChanging(short value);
    partial void OnadetChanged();
    partial void OnfiyatChanging(double value);
    partial void OnfiyatChanged();
    partial void OnoyunTur_idChanging(short value);
    partial void OnoyunTur_idChanged();
    #endregion
		
		public dt_oyun()
		{
			this._tx_satis = new EntitySet<tx_sati>(new Action<tx_sati>(this.attach_tx_satis), new Action<tx_sati>(this.detach_tx_satis));
			this._lu_oyunTur = default(EntityRef<lu_oyunTur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yapimYil", DbType="SmallInt NOT NULL")]
		public short yapimYil
		{
			get
			{
				return this._yapimYil;
			}
			set
			{
				if ((this._yapimYil != value))
				{
					this.OnyapimYilChanging(value);
					this.SendPropertyChanging();
					this._yapimYil = value;
					this.SendPropertyChanged("yapimYil");
					this.OnyapimYilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yapimci", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string yapimci
		{
			get
			{
				return this._yapimci;
			}
			set
			{
				if ((this._yapimci != value))
				{
					this.OnyapimciChanging(value);
					this.SendPropertyChanging();
					this._yapimci = value;
					this.SendPropertyChanged("yapimci");
					this.OnyapimciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string platform
		{
			get
			{
				return this._platform;
			}
			set
			{
				if ((this._platform != value))
				{
					this.OnplatformChanging(value);
					this.SendPropertyChanging();
					this._platform = value;
					this.SendPropertyChanged("platform");
					this.OnplatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barkod", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string barkod
		{
			get
			{
				return this._barkod;
			}
			set
			{
				if ((this._barkod != value))
				{
					this.OnbarkodChanging(value);
					this.SendPropertyChanging();
					this._barkod = value;
					this.SendPropertyChanged("barkod");
					this.OnbarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="SmallInt NOT NULL")]
		public short adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this.OnadetChanging(value);
					this.SendPropertyChanging();
					this._adet = value;
					this.SendPropertyChanged("adet");
					this.OnadetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="Float NOT NULL")]
		public double fiyat
		{
			get
			{
				return this._fiyat;
			}
			set
			{
				if ((this._fiyat != value))
				{
					this.OnfiyatChanging(value);
					this.SendPropertyChanging();
					this._fiyat = value;
					this.SendPropertyChanged("fiyat");
					this.OnfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oyunTur_id", DbType="SmallInt NOT NULL")]
		public short oyunTur_id
		{
			get
			{
				return this._oyunTur_id;
			}
			set
			{
				if ((this._oyunTur_id != value))
				{
					if (this._lu_oyunTur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnoyunTur_idChanging(value);
					this.SendPropertyChanging();
					this._oyunTur_id = value;
					this.SendPropertyChanged("oyunTur_id");
					this.OnoyunTur_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_oyun_tx_sati", Storage="_tx_satis", ThisKey="id", OtherKey="oyun_id")]
		public EntitySet<tx_sati> tx_satis
		{
			get
			{
				return this._tx_satis;
			}
			set
			{
				this._tx_satis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lu_oyunTur_dt_oyun", Storage="_lu_oyunTur", ThisKey="oyunTur_id", OtherKey="id", IsForeignKey=true)]
		public lu_oyunTur lu_oyunTur
		{
			get
			{
				return this._lu_oyunTur.Entity;
			}
			set
			{
				lu_oyunTur previousValue = this._lu_oyunTur.Entity;
				if (((previousValue != value) 
							|| (this._lu_oyunTur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lu_oyunTur.Entity = null;
						previousValue.dt_oyuns.Remove(this);
					}
					this._lu_oyunTur.Entity = value;
					if ((value != null))
					{
						value.dt_oyuns.Add(this);
						this._oyunTur_id = value.id;
					}
					else
					{
						this._oyunTur_id = default(short);
					}
					this.SendPropertyChanged("lu_oyunTur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tx_satis(tx_sati entity)
		{
			this.SendPropertyChanging();
			entity.dt_oyun = this;
		}
		
		private void detach_tx_satis(tx_sati entity)
		{
			this.SendPropertyChanging();
			entity.dt_oyun = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lu_filmTur")]
	public partial class lu_filmTur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _id;
		
		private string _ad;
		
		private EntitySet<dt_film> _dt_films;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(short value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    #endregion
		
		public lu_filmTur()
		{
			this._dt_films = new EntitySet<dt_film>(new Action<dt_film>(this.attach_dt_films), new Action<dt_film>(this.detach_dt_films));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lu_filmTur_dt_film", Storage="_dt_films", ThisKey="id", OtherKey="filmTur_id")]
		public EntitySet<dt_film> dt_films
		{
			get
			{
				return this._dt_films;
			}
			set
			{
				this._dt_films.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dt_films(dt_film entity)
		{
			this.SendPropertyChanging();
			entity.lu_filmTur = this;
		}
		
		private void detach_dt_films(dt_film entity)
		{
			this.SendPropertyChanging();
			entity.lu_filmTur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lu_oyunTur")]
	public partial class lu_oyunTur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _id;
		
		private string _ad;
		
		private EntitySet<dt_oyun> _dt_oyuns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(short value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    #endregion
		
		public lu_oyunTur()
		{
			this._dt_oyuns = new EntitySet<dt_oyun>(new Action<dt_oyun>(this.attach_dt_oyuns), new Action<dt_oyun>(this.detach_dt_oyuns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lu_oyunTur_dt_oyun", Storage="_dt_oyuns", ThisKey="id", OtherKey="oyunTur_id")]
		public EntitySet<dt_oyun> dt_oyuns
		{
			get
			{
				return this._dt_oyuns;
			}
			set
			{
				this._dt_oyuns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dt_oyuns(dt_oyun entity)
		{
			this.SendPropertyChanging();
			entity.lu_oyunTur = this;
		}
		
		private void detach_dt_oyuns(dt_oyun entity)
		{
			this.SendPropertyChanging();
			entity.lu_oyunTur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tx_filmKira")]
	public partial class tx_filmKira : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private int _kullanici_id;
		
		private int _film_id;
		
		private short _adet;
		
		private System.Nullable<double> _ucret;
		
		private System.DateTime _alinanTarih;
		
		private System.DateTime _iadeTarih;
		
		private System.Nullable<System.DateTime> _teslimTarih;
		
		private EntityRef<dt_kullanici> _dt_kullanici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onkullanici_idChanging(int value);
    partial void Onkullanici_idChanged();
    partial void Onfilm_idChanging(int value);
    partial void Onfilm_idChanged();
    partial void OnadetChanging(short value);
    partial void OnadetChanged();
    partial void OnucretChanging(System.Nullable<double> value);
    partial void OnucretChanged();
    partial void OnalinanTarihChanging(System.DateTime value);
    partial void OnalinanTarihChanged();
    partial void OniadeTarihChanging(System.DateTime value);
    partial void OniadeTarihChanged();
    partial void OnteslimTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnteslimTarihChanged();
    #endregion
		
		public tx_filmKira()
		{
			this._dt_kullanici = default(EntityRef<dt_kullanici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_id", DbType="Int NOT NULL")]
		public int kullanici_id
		{
			get
			{
				return this._kullanici_id;
			}
			set
			{
				if ((this._kullanici_id != value))
				{
					if (this._dt_kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkullanici_idChanging(value);
					this.SendPropertyChanging();
					this._kullanici_id = value;
					this.SendPropertyChanged("kullanici_id");
					this.Onkullanici_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_id", DbType="Int NOT NULL")]
		public int film_id
		{
			get
			{
				return this._film_id;
			}
			set
			{
				if ((this._film_id != value))
				{
					this.Onfilm_idChanging(value);
					this.SendPropertyChanging();
					this._film_id = value;
					this.SendPropertyChanged("film_id");
					this.Onfilm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="SmallInt NOT NULL")]
		public short adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this.OnadetChanging(value);
					this.SendPropertyChanging();
					this._adet = value;
					this.SendPropertyChanged("adet");
					this.OnadetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucret", DbType="Float")]
		public System.Nullable<double> ucret
		{
			get
			{
				return this._ucret;
			}
			set
			{
				if ((this._ucret != value))
				{
					this.OnucretChanging(value);
					this.SendPropertyChanging();
					this._ucret = value;
					this.SendPropertyChanged("ucret");
					this.OnucretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alinanTarih", DbType="Date NOT NULL")]
		public System.DateTime alinanTarih
		{
			get
			{
				return this._alinanTarih;
			}
			set
			{
				if ((this._alinanTarih != value))
				{
					this.OnalinanTarihChanging(value);
					this.SendPropertyChanging();
					this._alinanTarih = value;
					this.SendPropertyChanged("alinanTarih");
					this.OnalinanTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iadeTarih", DbType="Date NOT NULL")]
		public System.DateTime iadeTarih
		{
			get
			{
				return this._iadeTarih;
			}
			set
			{
				if ((this._iadeTarih != value))
				{
					this.OniadeTarihChanging(value);
					this.SendPropertyChanging();
					this._iadeTarih = value;
					this.SendPropertyChanged("iadeTarih");
					this.OniadeTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teslimTarih", DbType="Date")]
		public System.Nullable<System.DateTime> teslimTarih
		{
			get
			{
				return this._teslimTarih;
			}
			set
			{
				if ((this._teslimTarih != value))
				{
					this.OnteslimTarihChanging(value);
					this.SendPropertyChanging();
					this._teslimTarih = value;
					this.SendPropertyChanged("teslimTarih");
					this.OnteslimTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_kullanici_tx_filmKira", Storage="_dt_kullanici", ThisKey="kullanici_id", OtherKey="id", IsForeignKey=true)]
		public dt_kullanici dt_kullanici
		{
			get
			{
				return this._dt_kullanici.Entity;
			}
			set
			{
				dt_kullanici previousValue = this._dt_kullanici.Entity;
				if (((previousValue != value) 
							|| (this._dt_kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dt_kullanici.Entity = null;
						previousValue.tx_filmKiras.Remove(this);
					}
					this._dt_kullanici.Entity = value;
					if ((value != null))
					{
						value.tx_filmKiras.Add(this);
						this._kullanici_id = value.id;
					}
					else
					{
						this._kullanici_id = default(int);
					}
					this.SendPropertyChanged("dt_kullanici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tx_satis")]
	public partial class tx_sati : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<int> _film_id;
		
		private System.Nullable<int> _muzik_id;
		
		private System.Nullable<int> _oyun_id;
		
		private int _kullanici_id;
		
		private System.DateTime _tarih;
		
		private short _adet;
		
		private double _ucret;
		
		private EntityRef<dt_film> _dt_film;
		
		private EntityRef<dt_kullanici> _dt_kullanici;
		
		private EntityRef<dt_muzik> _dt_muzik;
		
		private EntityRef<dt_oyun> _dt_oyun;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onfilm_idChanging(System.Nullable<int> value);
    partial void Onfilm_idChanged();
    partial void Onmuzik_idChanging(System.Nullable<int> value);
    partial void Onmuzik_idChanged();
    partial void Onoyun_idChanging(System.Nullable<int> value);
    partial void Onoyun_idChanged();
    partial void Onkullanici_idChanging(int value);
    partial void Onkullanici_idChanged();
    partial void OntarihChanging(System.DateTime value);
    partial void OntarihChanged();
    partial void OnadetChanging(short value);
    partial void OnadetChanged();
    partial void OnucretChanging(double value);
    partial void OnucretChanged();
    #endregion
		
		public tx_sati()
		{
			this._dt_film = default(EntityRef<dt_film>);
			this._dt_kullanici = default(EntityRef<dt_kullanici>);
			this._dt_muzik = default(EntityRef<dt_muzik>);
			this._dt_oyun = default(EntityRef<dt_oyun>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_id", DbType="Int")]
		public System.Nullable<int> film_id
		{
			get
			{
				return this._film_id;
			}
			set
			{
				if ((this._film_id != value))
				{
					if (this._dt_film.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfilm_idChanging(value);
					this.SendPropertyChanging();
					this._film_id = value;
					this.SendPropertyChanged("film_id");
					this.Onfilm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_muzik_id", DbType="Int")]
		public System.Nullable<int> muzik_id
		{
			get
			{
				return this._muzik_id;
			}
			set
			{
				if ((this._muzik_id != value))
				{
					if (this._dt_muzik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmuzik_idChanging(value);
					this.SendPropertyChanging();
					this._muzik_id = value;
					this.SendPropertyChanged("muzik_id");
					this.Onmuzik_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oyun_id", DbType="Int")]
		public System.Nullable<int> oyun_id
		{
			get
			{
				return this._oyun_id;
			}
			set
			{
				if ((this._oyun_id != value))
				{
					if (this._dt_oyun.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onoyun_idChanging(value);
					this.SendPropertyChanging();
					this._oyun_id = value;
					this.SendPropertyChanged("oyun_id");
					this.Onoyun_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_id", DbType="Int NOT NULL")]
		public int kullanici_id
		{
			get
			{
				return this._kullanici_id;
			}
			set
			{
				if ((this._kullanici_id != value))
				{
					if (this._dt_kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkullanici_idChanging(value);
					this.SendPropertyChanging();
					this._kullanici_id = value;
					this.SendPropertyChanged("kullanici_id");
					this.Onkullanici_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="Date NOT NULL")]
		public System.DateTime tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this.OntarihChanging(value);
					this.SendPropertyChanging();
					this._tarih = value;
					this.SendPropertyChanged("tarih");
					this.OntarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="SmallInt NOT NULL")]
		public short adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this.OnadetChanging(value);
					this.SendPropertyChanging();
					this._adet = value;
					this.SendPropertyChanged("adet");
					this.OnadetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucret", DbType="Float NOT NULL")]
		public double ucret
		{
			get
			{
				return this._ucret;
			}
			set
			{
				if ((this._ucret != value))
				{
					this.OnucretChanging(value);
					this.SendPropertyChanging();
					this._ucret = value;
					this.SendPropertyChanged("ucret");
					this.OnucretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_film_tx_sati", Storage="_dt_film", ThisKey="film_id", OtherKey="id", IsForeignKey=true)]
		public dt_film dt_film
		{
			get
			{
				return this._dt_film.Entity;
			}
			set
			{
				dt_film previousValue = this._dt_film.Entity;
				if (((previousValue != value) 
							|| (this._dt_film.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dt_film.Entity = null;
						previousValue.tx_satis.Remove(this);
					}
					this._dt_film.Entity = value;
					if ((value != null))
					{
						value.tx_satis.Add(this);
						this._film_id = value.id;
					}
					else
					{
						this._film_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("dt_film");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_kullanici_tx_sati", Storage="_dt_kullanici", ThisKey="kullanici_id", OtherKey="id", IsForeignKey=true)]
		public dt_kullanici dt_kullanici
		{
			get
			{
				return this._dt_kullanici.Entity;
			}
			set
			{
				dt_kullanici previousValue = this._dt_kullanici.Entity;
				if (((previousValue != value) 
							|| (this._dt_kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dt_kullanici.Entity = null;
						previousValue.tx_satis.Remove(this);
					}
					this._dt_kullanici.Entity = value;
					if ((value != null))
					{
						value.tx_satis.Add(this);
						this._kullanici_id = value.id;
					}
					else
					{
						this._kullanici_id = default(int);
					}
					this.SendPropertyChanged("dt_kullanici");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_muzik_tx_sati", Storage="_dt_muzik", ThisKey="muzik_id", OtherKey="id", IsForeignKey=true)]
		public dt_muzik dt_muzik
		{
			get
			{
				return this._dt_muzik.Entity;
			}
			set
			{
				dt_muzik previousValue = this._dt_muzik.Entity;
				if (((previousValue != value) 
							|| (this._dt_muzik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dt_muzik.Entity = null;
						previousValue.tx_satis.Remove(this);
					}
					this._dt_muzik.Entity = value;
					if ((value != null))
					{
						value.tx_satis.Add(this);
						this._muzik_id = value.id;
					}
					else
					{
						this._muzik_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("dt_muzik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dt_oyun_tx_sati", Storage="_dt_oyun", ThisKey="oyun_id", OtherKey="id", IsForeignKey=true)]
		public dt_oyun dt_oyun
		{
			get
			{
				return this._dt_oyun.Entity;
			}
			set
			{
				dt_oyun previousValue = this._dt_oyun.Entity;
				if (((previousValue != value) 
							|| (this._dt_oyun.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dt_oyun.Entity = null;
						previousValue.tx_satis.Remove(this);
					}
					this._dt_oyun.Entity = value;
					if ((value != null))
					{
						value.tx_satis.Add(this);
						this._oyun_id = value.id;
					}
					else
					{
						this._oyun_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("dt_oyun");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lu_muzikTur")]
	public partial class lu_muzikTur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _id;
		
		private string _ad;
		
		private EntitySet<dt_muzik> _dt_muziks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(short value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    #endregion
		
		public lu_muzikTur()
		{
			this._dt_muziks = new EntitySet<dt_muzik>(new Action<dt_muzik>(this.attach_dt_muziks), new Action<dt_muzik>(this.detach_dt_muziks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lu_muzikTur_dt_muzik", Storage="_dt_muziks", ThisKey="id", OtherKey="muzikTur_id")]
		public EntitySet<dt_muzik> dt_muziks
		{
			get
			{
				return this._dt_muziks;
			}
			set
			{
				this._dt_muziks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dt_muziks(dt_muzik entity)
		{
			this.SendPropertyChanging();
			entity.lu_muzikTur = this;
		}
		
		private void detach_dt_muziks(dt_muzik entity)
		{
			this.SendPropertyChanging();
			entity.lu_muzikTur = null;
		}
	}
}
#pragma warning restore 1591
